// generated by Fast Light User Interface Designer (fluid) version 1.0300

#ifndef Editor_h
#define Editor_h
#include <FL/Fl.H>
#include <stdlib.h>
#include <Fl/Fl_Text_Buffer.h>
#include "Fl_Split.h"
#include <FL/Fl_Group.h>
#include <FL/Fl_Text_Editor.H>
#include <Fl/Fl_PNM_Image.h>
#include "systemdirectorybrowser/fl_systemdirectory_browser.h"
#include "FontBrowser/fl_font_browser.h"
#include "ColorBrowser/fl_color_direct_selector.h"
#include <Fl/Fl_Shared_Image.h>
#include <Fl/Fl_Button.h>
#include <FL/Fl_File_Chooser.H>
#include <FL/fl_ask.H>
#include <stdio.h>
#include <iostream>
#include <errno.h>

class Fl_Ext_Text_Editor : public Fl_Text_Editor {
public:
  int SetNew; 
  Fl_Ext_Text_Editor(int x, int y, int w, int h, char*l);
  ~Fl_Ext_Text_Editor();
  int GetCursorPosition();
  static void blinkCursor(void* TxtObject);
};

class Fl_Preview_Image : public Fl_Group {
public:
  Fl_Preview_Image(int x, int y, int w, int h, char*l);
  virtual int handle(int e);
  int Xclicked,Yclicked; 
};

class Fl_New_File : public Fl_Group {
public:
  Fl_Ext_Text_Editor *e; 
  Fl_Text_Buffer  *t; 
  Fl_Button *b; 
  int changed; 
  static int counter; 
  char fileName[4056]; 
  Fl_New_File *pNext; 
  Fl_New_File *pPrev; 
  int NotSaved; // 1 true 0 false
  Fl_New_File(int x, int y, int w, int h, char*l);
  ~Fl_New_File();
};

class GetDir : public Fl_SystemDirectory_Browser {
public:
  GetDir( int x, int y, int w, int h, char* l);
  int HandleSelect(Fl_Ext_TreeItem* pItem, int bState);
};
void cb_PreviewBoxClicked(Fl_Widget* w, void*gg);
void cb_InsertTag(Fl_Widget*, void* Tag);
void cb_tab_FileManager(Fl_Widget*  , void* getdata);
void cb_ShowPicturePreview(void);
void GetPixelColorOfImage(void *imagePointer, int x,int y,  uchar &r, uchar  &g, uchar &b);
void load_file(char *newfile);
#include <FL/Fl_Double_Window.H>
extern Fl_Double_Window *window;
#include <FL/Fl_Tabs.H>
#include <FL/Fl_Group.H>
extern Fl_Group *mnu_Tab_Text;
#include <FL/Fl_Button.H>
extern Fl_Group *mnu_Tab_Table;
#include <FL/Fl_Box.H>
#include <FL/Fl_Value_Input.H>
extern Fl_Value_Input *mnu_Table_Column;
#include <FL/Fl_Repeat_Button.H>
extern Fl_Value_Input *mnu_Table_Row;
extern Fl_Group *mnu_Tab_List;
extern Fl_Group *mnu_Tab_Css;
extern Fl_Group *mnu_Tab_Equations;
extern Fl_Group *mnu_Tab_Java;
#include <FL/Fl_Menu_Button.H>
extern Fl_Group *mnu_Tab_VBScript;
extern Fl_Group *mnu_Tab_Colors;
extern Fl_Color_Direct_Selector *mnu_Color_Selector;
extern Fl_Group *mnu_Tab_Paramiter;
#include <FL/Fl_Input.H>
extern Fl_Input *txt_Parameter;
#include <FL/Fl_Menu_Bar.H>
extern Fl_Menu_Bar *Editor_Meny_File;
extern Fl_Tabs *tab_FileManager;
extern Fl_Group *tab_Editor_View;
extern Fl_Group *tab_Picture_View;
extern Fl_Group *tab_Browser_View;
extern Fl_Tabs *txt_Tab_Edit;
extern Fl_New_File *txtEditorTemplate;
extern Fl_Button *btn_File_New;
extern Fl_Button *btn_File_Open;
extern Fl_Button *btn_File_Close;
extern Fl_Button *btn_File_Save;
extern Fl_Button *btn_File_SaveAll;
extern Fl_Button *btn_File_Backup;
extern Fl_Button *btn_Edit_Cut;
extern Fl_Button *btn_Edit_Copy;
extern Fl_Button *btn_Edit_Paste;
extern Fl_Button *btn_Edit_Undo;
extern Fl_Button *btn_Edit_Redo;
extern Fl_Button *btn_Insert_Hyperlink;
extern Fl_Button *btn_Insert_EmailAddress;
extern Fl_Button *btn_Insert_Anchor;
extern Fl_Button *btn_Insert_HLine;
extern Fl_Button *btn_Insert_Picture;
extern Fl_Button *btn_Insert_HomeAdress;
extern Fl_Button *btn_Insert_EmailCust;
extern Fl_Button *btn_Insert_Favorite;
extern Fl_Menu_Button *mnu_File_Preview;
extern Fl_Group *gr_btn_textSize;
extern Fl_Button *btn_HideShow;
extern Fl_Group *gr_View_Picture;
extern Fl_Preview_Image *previewBox;
#include <FL/Fl_Output.H>
extern Fl_Output *lbClickedColor;
extern Fl_Button *btnCopyColorCode;
extern Fl_Group *gr_View_Browser;
#include <FL/Fl_Help_View.H>
extern Fl_Help_View *hv_Browser;
#include <FL/Fl_File_Browser.H>
extern Fl_File_Browser *fl_File_View;
extern GetDir *direcotryBrowser;
extern Fl_Menu_Item menu_events[];
extern Fl_Menu_Item menu_events1[];
extern Fl_Menu_Item menu_Editor_Meny_File[];
#define mnu_File (menu_Editor_Meny_File+0)
#define mnu_New (menu_Editor_Meny_File+1)
#define mnu_History (menu_Editor_Meny_File+2)
#define mnu_ClearHistory (menu_Editor_Meny_File+3)
#define mnu_Open (menu_Editor_Meny_File+5)
#define Sub_mnu_ShowFile (menu_Editor_Meny_File+6)
#define mnu_NextFile (menu_Editor_Meny_File+8)
#define mnu_LastFile (menu_Editor_Meny_File+9)
#define mnu_Save (menu_Editor_Meny_File+10)
#define mnu_SaveAs (menu_Editor_Meny_File+11)
#define mnu_SaveAsLinux (menu_Editor_Meny_File+12)
#define mnu_SaveAll (menu_Editor_Meny_File+13)
#define mnu_Close (menu_Editor_Meny_File+14)
#define mnu_Exit (menu_Editor_Meny_File+15)
#define mnu_Edit (menu_Editor_Meny_File+17)
#define mnu_Undo (menu_Editor_Meny_File+18)
#define mnu_Redo (menu_Editor_Meny_File+19)
#define mnu_Cut (menu_Editor_Meny_File+20)
#define mnu_Copy (menu_Editor_Meny_File+21)
#define mnu_Paste (menu_Editor_Meny_File+22)
#define mnu_Delete (menu_Editor_Meny_File+23)
#define mnu_SelectAll (menu_Editor_Meny_File+24)
#define mnu_Tab (menu_Editor_Meny_File+25)
#define mnu_ReverseTab (menu_Editor_Meny_File+26)
#define mnu_Find (menu_Editor_Meny_File+27)
#define mnu_FindNext (menu_Editor_Meny_File+28)
#define mnu_Replace (menu_Editor_Meny_File+29)
#define mnu_Goto (menu_Editor_Meny_File+30)
#define mnu_Insert (menu_Editor_Meny_File+32)
#define mnu_Hyperlink (menu_Editor_Meny_File+33)
#define mnu_Yourhomesite (menu_Editor_Meny_File+34)
#define mnu_EmailAdress (menu_Editor_Meny_File+35)
#define mnu_YourEmail (menu_Editor_Meny_File+36)
#define mnu_Anker (menu_Editor_Meny_File+37)
#define mnu_HorisontalLine (menu_Editor_Meny_File+38)
#define mnu_Picture (menu_Editor_Meny_File+39)
#define mnu_RGB (menu_Editor_Meny_File+40)
#define mnu_Date (menu_Editor_Meny_File+41)
#define mnu_Automatic (menu_Editor_Meny_File+42)
#define mnu_20071029 (menu_Editor_Meny_File+44)
#define mnu_Format (menu_Editor_Meny_File+47)
#define mnu_Title (menu_Editor_Meny_File+48)
#define mnu_H1 (menu_Editor_Meny_File+49)
#define mnu_H2 (menu_Editor_Meny_File+50)
#define mnu_H3 (menu_Editor_Meny_File+51)
#define mnu_H4 (menu_Editor_Meny_File+52)
#define mnu_H5 (menu_Editor_Meny_File+53)
#define mnu_H6 (menu_Editor_Meny_File+54)
#define mnu_Text (menu_Editor_Meny_File+56)
#define mnu_acronym (menu_Editor_Meny_File+57)
#define mnu_Address (menu_Editor_Meny_File+58)
#define mnu_Em (menu_Editor_Meny_File+59)
#define mnu_Blockquote (menu_Editor_Meny_File+60)
#define mnu_Sample (menu_Editor_Meny_File+61)
#define mnu_Code (menu_Editor_Meny_File+62)
#define mnu_Definition (menu_Editor_Meny_File+63)
#define mnu_Big (menu_Editor_Meny_File+64)
#define mnu_Strong (menu_Editor_Meny_File+65)
#define mnu_Keyboard (menu_Editor_Meny_File+66)
#define mnu_Small (menu_Editor_Meny_File+67)
#define mnu_Listing (menu_Editor_Meny_File+68)
#define mnu_Typewriter (menu_Editor_Meny_File+69)
#define mnu_Comment (menu_Editor_Meny_File+70)
#define mnu_Preformatted (menu_Editor_Meny_File+71)
#define mnu_Variable (menu_Editor_Meny_File+72)
#define mnu_Citation (menu_Editor_Meny_File+73)
#define mnu_CitationWith (menu_Editor_Meny_File+74)
#define mnu_Paragraph (menu_Editor_Meny_File+76)
#define mnu_Paragraph (menu_Editor_Meny_File+77)
#define mnu_Font (menu_Editor_Meny_File+79)
#define mnu_FontSize (menu_Editor_Meny_File+80)
#define mnu_PlusFour (menu_Editor_Meny_File+81)
#define mnu_PlusThree (menu_Editor_Meny_File+82)
#define mnu_PlusTwo (menu_Editor_Meny_File+83)
#define mnu_PlusOne (menu_Editor_Meny_File+84)
#define mnu_MinusOne (menu_Editor_Meny_File+85)
#define mnu_MinusTwo (menu_Editor_Meny_File+86)
#define mnu_BaseFont (menu_Editor_Meny_File+87)
#define mnu_FontFormat (menu_Editor_Meny_File+89)
#define mnu_FontArial (menu_Editor_Meny_File+90)
#define mnu_FontCourier (menu_Editor_Meny_File+91)
#define mnu_FontMonospace (menu_Editor_Meny_File+92)
#define mnu_FontSelect (menu_Editor_Meny_File+93)
#define mnu_FontColor (menu_Editor_Meny_File+95)
#define mnu_FontBold (menu_Editor_Meny_File+96)
#define mnu_FontItalic (menu_Editor_Meny_File+97)
#define mnu_FontUnderLine (menu_Editor_Meny_File+98)
#define mnu_SuperScript (menu_Editor_Meny_File+99)
#define mnu_FontSubScript (menu_Editor_Meny_File+100)
#define mnu_FontStrick (menu_Editor_Meny_File+101)
#define mnu_FontScrollingText (menu_Editor_Meny_File+102)
#define mnu_ToolsDebuger (menu_Editor_Meny_File+105)
#define mnu_ToolsHTMLConstructor (menu_Editor_Meny_File+106)
#define mnu_ToolsTableAssistant (menu_Editor_Meny_File+107)
extern Fl_Menu_Item menu_mnu_File_Preview[];
#define btn_File_Preview (menu_mnu_File_Preview+0)
#define btn_File_Prev_IExplorer (menu_mnu_File_Preview+1)
extern Fl_Double_Window *frmAbout;
void Getabout();
void cb_File_Open();
void cb_File_New();
int check_save(void);
void cb_File_Close();
void cb_File_Save(char* newfile);
void cb_File_SaveAll();
void cb_File_Backup();
void cb_Edit_Cut();
void cb_Edit_Paste();
void cb_Edit_Undo();
void cb_Edit_Redo();
void cb_Insert_Hyperlink();
void cb_Insert_EmailAddress();
void cb_Insert_Anchor();
void cb_Insert_HLine();
void cb_Insert_Picture();
void cb_Insert_HomeAdress();
void cb_Insert_EmailCust();
void cb_Insert_Favorite();
void cb_File_Pr_IExplorer();
void cb_mnuText_Paragraph();
void cb_mnuText_Align_Left();
void cb_mnuText_Align_Center();
void cb_mnuText_Align_Justify();
void cb_mnuText_Indent();
void cb_mnuText_Format_Bold();
void cb_mnuText_Format_Italic();
void cb_mnuText_Format_Underline();
void cb_mnuText_Format_Superscript();
void cb_mnuText_Format_Subscript();
void cb_mnuText_Format_PRE();
void cb_mnuText_Format_H1();
void cb_mnuText_Format_H2();
void cb_mnuText_Format_H3();
void cb_mnuText_Format_H4();
void cb_mnuText_Format_H5();
void cb_mnuText_Format_Plus4();
void cb_mnuText_Format_Plus3();
void cb_mnuText_Format_Plus2();
void cb_mnuText_Format_Plus1();
void cb_mnuText_Format_Minus1();
void cb_mnuText_Format_FontStyle();
void cb_mnuText_Format_Break();
extern Fl_Double_Window *frm_Table_Assistant;
#include <FL/Fl_Tile.H>
extern Fl_Value_Input *frm_Table_Row;
extern Fl_Value_Input *frm_Table_Column;
void cb_Table_Assistant();
void cb_mnuText_Align_Right();
void cb_Edit_Copy();
void cb_File_Preview();
char* InsertTagWithAText(const char* TagOrigional, const char* GetSymbol, const char* TextInTag);
void changed_cb(void*, void* ChangedFile);
void Style_Color_determine(int        pos,		// I - Position of update
             int        nInserted,	// I - Number of inserted chars
	     int        nDeleted,	// I - Number of deleted chars
             int        /*nRestyled*/,	// I - Number of restyled chars
	     const char * /*deletedText*/,// I - Text that was deleted
             void       *cbArg);
int cb_File_SaveAs(void);
void cb_Select_Font(Fl_Widget*, void*);
void cb_ColorSelector_Clicked(Fl_Widget*, void* wid);
void cb_Copy_Color_Code(Fl_Widget*, void* cpCode);
void cb_SelectFont(Fl_Widget* , void* frmT);
void cb_FontBrowser(Fl_Widget*,  void* frm_FontBrowser);
void cb_TabNext();
void cb_TabPrev();
#endif
