# Project: Project1
# Makefile created by Dev-C++ 5.2.0.3

CPP      = g++.exe -D__DEBUG__
CC       = gcc.exe -D__DEBUG__
WINDRES  = windres.exe
RES      = ../fltk_editor/editor_private.res
OBJ      = ../fltk_editor/Editor.o ../fltk_editor/fl_systemdirectory_browser.o ../fltk_editor/fl_color_direct_selector.o ../fltk_editor/fl_font_browser.o ../fltk_editor/vsnprintf.o ../fltk_editor/fl_ext_tree_browser.o ../fltk_editor/fl_ext_tree_item.o ../fltk_editor/flstring.o $(RES)
LINKOBJ  = ../fltk_editor/Editor.o ../fltk_editor/fl_systemdirectory_browser.o ../fltk_editor/fl_color_direct_selector.o ../fltk_editor/fl_font_browser.o ../fltk_editor/vsnprintf.o ../fltk_editor/fl_ext_tree_browser.o ../fltk_editor/fl_ext_tree_item.o ../fltk_editor/flstring.o $(RES)
LIBS     = -pg -L"C:/Dev-Cpp/MinGW32/lib" -L"C:/Dev-Cpp/lib" -static-libstdc++ -static-libgcc -L"C:/Documents and Settings/Mariwa/Skrivbord/testme/fltk_editor/fltk_editor/ColorBrowser" -L"C:/Documents and Settings/Mariwa/Skrivbord/testme/fltk_editor/fltk_editor/FontBrowser" -L"C:/Documents and Settings/Mariwa/Skrivbord/testme/fltk_editor/fltk_editor/systemdirectorybrowser" -L"C:/Documents and Settings/Mariwa/Skrivbord/testme/fltk_editor/fltk_editor" -mwindows -lfltk -lfltk_forms -lfltk_gl -lfltk_images -lfltk_jpeg -lfltk_png -lfltk_z -lole32 -lgdi32 -luuid -lcomctl32 -lcomdlg32 -lwsock32 -lole32 -luuid -lcomctl32 -lwsock32 -lm -lfltk_images -lfltk_jpeg -lfltk_png   -g3 
INCS     = -I"C:/Dev-Cpp/MinGW32/include"  -I"C:/Dev-Cpp/include"  -I"C:/Documents and Settings/Mariwa/Skrivbord/testme/fltk_editor/fltk_editor"  -I"C:/Documents and Settings/Mariwa/Skrivbord/testme/fltk_editor/fltk_editor/ColorBrowser"  -I"C:/Documents and Settings/Mariwa/Skrivbord/testme/fltk_editor/fltk_editor/systemdirectorybrowser"  -I"C:/Documents and Settings/Mariwa/Skrivbord/testme/fltk_editor/fltk_editor/FontBrowser" 
CXXINCS  = -I"C:/Dev-Cpp/MinGW32/include"  -I"C:/Dev-Cpp/include"  -I"C:/Documents and Settings/Mariwa/Skrivbord/testme/fltk_editor/fltk_editor"  -I"C:/Documents and Settings/Mariwa/Skrivbord/testme/fltk_editor/fltk_editor/ColorBrowser"  -I"C:/Documents and Settings/Mariwa/Skrivbord/testme/fltk_editor/fltk_editor/systemdirectorybrowser"  -I"C:/Documents and Settings/Mariwa/Skrivbord/testme/fltk_editor/fltk_editor/FontBrowser" 
BIN      = Editor.exe
CXXFLAGS = $(CXXINCS)   -w -pg -g3 -fverbose-asm
CFLAGS   = $(INCS) -DWIN32 -mms-bitfields   -w -pg -g3 -fverbose-asm
RM       = rm -f

.PHONY: all all-before all-after clean clean-custom

all: all-before Editor.exe all-after


clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o "Editor.exe" $(LIBS)

../fltk_editor/Editor.o: Editor.cpp
	$(CPP) -c Editor.cpp -o ../fltk_editor/Editor.o $(CXXFLAGS)

../fltk_editor/fl_systemdirectory_browser.o: systemdirectorybrowser/fl_systemdirectory_browser.cpp
	$(CPP) -c systemdirectorybrowser/fl_systemdirectory_browser.cpp -o ../fltk_editor/fl_systemdirectory_browser.o $(CXXFLAGS)

../fltk_editor/fl_color_direct_selector.o: ColorBrowser/fl_color_direct_selector.cpp
	$(CPP) -c ColorBrowser/fl_color_direct_selector.cpp -o ../fltk_editor/fl_color_direct_selector.o $(CXXFLAGS)

../fltk_editor/fl_font_browser.o: FontBrowser/fl_font_browser.cpp
	$(CPP) -c FontBrowser/fl_font_browser.cpp -o ../fltk_editor/fl_font_browser.o $(CXXFLAGS)

../fltk_editor/vsnprintf.o: systemdirectorybrowser/vsnprintf.c
	$(CPP) -c systemdirectorybrowser/vsnprintf.c -o ../fltk_editor/vsnprintf.o $(CXXFLAGS)

../fltk_editor/fl_ext_tree_browser.o: systemdirectorybrowser/fl_ext_tree_browser.cpp
	$(CPP) -c systemdirectorybrowser/fl_ext_tree_browser.cpp -o ../fltk_editor/fl_ext_tree_browser.o $(CXXFLAGS)

../fltk_editor/fl_ext_tree_item.o: systemdirectorybrowser/fl_ext_tree_item.cpp
	$(CPP) -c systemdirectorybrowser/fl_ext_tree_item.cpp -o ../fltk_editor/fl_ext_tree_item.o $(CXXFLAGS)

../fltk_editor/flstring.o: systemdirectorybrowser/flstring.c
	$(CPP) -c systemdirectorybrowser/flstring.c -o ../fltk_editor/flstring.o $(CXXFLAGS)

../fltk_editor/editor_private.res: editor_private.rc 
	$(WINDRES) -i editor_private.rc --input-format=rc -o ../fltk_editor/editor_private.res -O coff  --include-dir C:/DOCUME~1/Mariwa/SKRIVB~1/testme/FLTK_E~1/FLTK_E~1
